setwd("D:/Git/datasciencecoursera") 
data_complete <- read.csv("household_power_consumption.txt",header = TRUE,sep=";")
data_subset <- subset(data_complete, Date %in% c("1/2/2007","2/2/2007"))
data_subset$Date <- as.Date(data_subset$Date, format="%d/%m/%Y")
Global_active_power <- as.numeric(data_subset$Global_active_power)
png("plot1.png", height=480, width=480)
hist(Global_active_power, main="Global Active Power",xlab="Global Active Power (in kilowatts)", ylab="Frequency", col="Red")
dev.off()